function fmriqa_v4( ...
	magick_path, ...
	spm12_path, ...
	out_path, ...
	t1_file, ...
	seg_file, ...
	fmri_file, ...
	project, ...
	subject, ...
	session, ...
	scan ...
	)

addpath(spm12_path);

%% TODO
% TSNR histogram?
%
% Add global time series to output files
%
% Add xyz trans/rot plot?
%
% Fix title / proj/subj/sess/scan / date into one line at top, shift up
% lowest plot on page 2
%
% Fourth page showing voxels lost due to realignment? Or, gray matter image
% with voxels having missing data? One color for out of slice before
% realignment, another color for after. This would need to be done in the
% T1 space
%
% Gzip all output images


%% Version check and initialize SPM
disp('Version check')
vercheck('R2015a','SPM12 (6225)',[]);
spm_jobman('initcfg');


%% Prepare input files and move to output directory
disp('Preparing inputs')
[t1_file,seg_file,fmri_file,origfmri_file] = setup( ...
	out_path,t1_file,seg_file,fmri_file);


%% Realignment
disp('Realignment')
[fmri_file,rfmri_file,meanfmri_file,rp_file] = realignment(fmri_file);


%% Coregister the T1 and seg to the mean fMRI
disp('Coregister')
rcseg_file = coregister( ...
	out_path,t1_file,seg_file,meanfmri_file);


%% Volume-to-volume (framewise) quality metrics
disp('Volume QA')
[med_displc,glob,FD,DVARS,mvt_file,tsnr_file,stats] = ...
	volume_quality(out_path,meanfmri_file,origfmri_file,rp_file);


%% Output PDF
disp('Generating PDF')
make_pdf( ...
	magick_path, ...
	out_path, ...
	seg_file, ...
	rcseg_file, ...
	meanfmri_file, ...
	origfmri_file, ...
	rfmri_file, ...
	mvt_file, ...
	tsnr_file, ...
	rp_file, ...
	med_displc, ...
	glob, FD, DVARS, ...
	project, subject, session, scan ...
	)


%% Gzip output images
system(['gzip -f ' out_path '/meanfmri.nii']);
system(['gzip -f ' out_path '/temporal_snr.nii']);
system(['gzip -f ' out_path '/voxel_displacement_mm_95prctile.nii']);



